USE hospital_queue;

INSERT INTO doctors
(doctor_id, doctor_name, department, specialization, status)
VALUES
('DR1', 'Dr. Amit Mehta', 'Orthopedics', 'Orthopedic Surgery', 'Available'),
('DR2', 'Dr. Neha Sharma', 'Cardiology', 'Cardiology', 'Available'),
('DR3', 'Dr. Raj Patel', 'General Surgery', 'General Surgery', 'Busy'),
('DR4', 'Dr. Priya Shah', 'Emergency', 'Emergency Medicine', 'Available'),
('DR5', 'Dr. Rahul Joshi', 'Radiology', 'Radiology', 'Available'),
('DR6', 'Dr. Sneha Kulkarni', 'Obstetrics', 'Obstetrics and Gynecology', 'Busy'),
('DR7', 'Dr. Arjun Deshmukh', 'Neurology', 'Neurology', 'Available'),
('DR8', 'Dr. Pooja Nair', 'Oncology', 'Oncology', 'Available'),
('DR9', 'Dr. Karan Gupta', 'Pediatrics', 'Pediatrics', 'Available'),
('DR10', 'Dr. Anjali Verma', 'Internal Medicine', 'Internal Medicine', 'Busy'),
('DR11', 'Dr. Rohan Mehta', 'Orthopedics', 'Orthopedic Surgery', 'Available'),
('DR12', 'Dr. Kavita Sharma', 'Cardiology', 'Cardiology', 'Available'),
('DR13', 'Dr. Suresh Patel', 'General Surgery', 'General Surgery', 'Busy'),
('DR14', 'Dr. Riya Shah', 'Emergency', 'Emergency Medicine', 'Available'),
('DR15', 'Dr. Nikhil Joshi', 'Radiology', 'Radiology', 'Available'),
('DR16', 'Dr. Ayesha Khan', 'Obstetrics', 'Obstetrics and Gynecology', 'Available'),
('DR17', 'Dr. Manish Deshmukh', 'Neurology', 'Neurology', 'Busy'),
('DR18', 'Dr. Simran Nair', 'Oncology', 'Oncology', 'Available'),
('DR19', 'Dr. Vivek Gupta', 'Pediatrics', 'Pediatrics', 'Available'),
('DR20', 'Dr. Meera Verma', 'Internal Medicine', 'Internal Medicine', 'Busy'),
('DR21', 'Dr. Akash Mehta', 'Orthopedics', 'Orthopedic Surgery', 'Available'),
('DR22', 'Dr. Shreya Sharma', 'Cardiology', 'Cardiology', 'Available'),
('DR23', 'Dr. Aditya Patel', 'General Surgery', 'General Surgery', 'Available'),
('DR24', 'Dr. Isha Shah', 'Emergency', 'Emergency Medicine', 'Busy'),
('DR25', 'Dr. Sameer Joshi', 'Radiology', 'Radiology', 'Available'),
('DR26', 'Dr. Nandini Kulkarni', 'Obstetrics', 'Obstetrics and Gynecology', 'Available'),
('DR27', 'Dr. Rohit Deshmukh', 'Neurology', 'Neurology', 'Busy'),
('DR28', 'Dr. Tanvi Nair', 'Oncology', 'Oncology', 'Available'),
('DR29', 'Dr. Harsh Gupta', 'Pediatrics', 'Pediatrics', 'Available'),
('DR30', 'Dr. Divya Verma', 'Internal Medicine', 'Internal Medicine', 'Available'),
('DR31', 'Dr. Kunal Mehta', 'Orthopedics', 'Orthopedic Surgery', 'Busy'),
('DR32', 'Dr. Radhika Sharma', 'Cardiology', 'Cardiology', 'Available'),
('DR33', 'Dr. Varun Patel', 'General Surgery', 'General Surgery', 'Available'),
('DR34', 'Dr. Snehal Shah', 'Emergency', 'Emergency Medicine', 'Available'),
('DR35', 'Dr. Manav Joshi', 'Radiology', 'Radiology', 'Busy'),
('DR36', 'Dr. Shalini Kulkarni', 'Obstetrics', 'Obstetrics and Gynecology', 'Available'),
('DR37', 'Dr. Yash Deshmukh', 'Neurology', 'Neurology', 'Available'),
('DR38', 'Dr. Ananya Nair', 'Oncology', 'Oncology', 'Busy'),
('DR39', 'Dr. Abhishek Gupta', 'Pediatrics', 'Pediatrics', 'Available'),
('DR40', 'Dr. Sakshi Verma', 'Internal Medicine', 'Internal Medicine', 'Available'),
('DR41', 'Dr. Pranav Mehta', 'Orthopedics', 'Orthopedic Surgery', 'Available'),
('DR42', 'Dr. Mitali Sharma', 'Cardiology', 'Cardiology', 'Busy'),
('DR43', 'Dr. Deepak Patel', 'General Surgery', 'General Surgery', 'Available'),
('DR44', 'Dr. Komal Shah', 'Emergency', 'Emergency Medicine', 'Available'),
('DR45', 'Dr. Vishal Joshi', 'Radiology', 'Radiology', 'Busy'),
('DR46', 'Dr. Ritu Kulkarni', 'Obstetrics', 'Obstetrics and Gynecology', 'Available'),
('DR47', 'Dr. Siddharth Deshmukh', 'Neurology', 'Neurology', 'Available'),
('DR48', 'Dr. Poonam Nair', 'Oncology', 'Oncology', 'Available'),
('DR49', 'Dr. Amit Gupta', 'Pediatrics', 'Pediatrics', 'Busy'),
('DR50', 'Dr. Priti Sharma', 'Internal Medicine', 'Internal Medicine', 'Available')
ON DUPLICATE KEY UPDATE
doctor_name = VALUES(doctor_name),
department = VALUES(department),
specialization = VALUES(specialization),
status = VALUES(status);
